import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/**
 * Concatenate CSS files from styles/ folder into styles.css
 * Order is defined explicitly for proper cascade
 */
function buildCSS() {
	const stylesDir = "./styles";
	const outputFile = "./styles.css";
	
	// Define order explicitly for proper CSS cascade
	const cssOrder = [
		"variables.css",
		"base.css", 
		"header.css",
		"board.css",
		"cards.css",
		"bookmarks.css",
		"modals.css",
		"embedded.css",
		"responsive.css"
	];
	
	const cssBanner = `/* ============================================
   Kanban 4000 - Generated Stylesheet
   
   DO NOT EDIT THIS FILE DIRECTLY!
   Edit files in ./styles/ folder instead.
   This file is auto-generated during build.
   ============================================ */

`;
	
	let combined = cssBanner;
	
	for (const file of cssOrder) {
		const filePath = path.join(stylesDir, file);
		if (fs.existsSync(filePath)) {
			const content = fs.readFileSync(filePath, "utf8");
			combined += `\n/* === ${file} === */\n${content}\n`;
		} else {
			console.warn(`Warning: CSS file not found: ${filePath}`);
		}
	}
	
	fs.writeFileSync(outputFile, combined);
	console.log(`✓ Built styles.css from ${cssOrder.length} source files`);
}

// Build CSS first
buildCSS();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
